### PR TITLE
Add beaver doc

### PR DESCRIPTION
**Pull request by gmuraru**

### CODE REVIEW

**Comment by gmuraru** [comment]
@jmaunon do you have any idea why the ```docformatter``` is not formatting all the files? (when I run it locally?)

**Comment by jmaunon** [comment]
> @jmaunon do you have any idea why the `docformatter` is not formatting all the files? (when I run it locally?)

I have checked with `-r` (recursive) option and I agree it does not work. I think that I am going to remove it becuase it is not as useful as I though

**Comment by jmaunon** [comment]
@gmuraru , Have you seen the comment from pep8speak? (I activated in my repo) Do you think this could be useful for SyMPC and other repos?

**Comment by gmuraru** [comment]
> @gmuraru , Have you seen the comment from pep8speak? (I activated in my repo) Do you think this could be useful for SyMPC and other repos?

Also talked with Theo regarding this.
I think that, for the moment, we should not have the bot leaving comments on the PR. A better option might be to enforce developers to have ```pre-commit``` installed. This would automatically run the checks and format the code/docs when doing a commit).
If the devs don't have the ```pre-commit``` installed, then they would see the PR failing, but I think it is a good practice for them to check the Github Actions and see why it failed.

**Pull request merged**
